config/routes.rb
Rails.application.routes.draw do
  root 'leader_boards#index'
  resources :matches
  resources :members
  resources :leader_boards, only: [:index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
    has_many :participants, dependent: :destroy
	accepts_nested_attributes_for :participants ,:allow_destroy => true
end

app/models/member.rb
class Member < ApplicationRecord
    has_many :participants, dependent: :destroy
end

app/models/participant.rb
class Participant < ApplicationRecord
    belongs_to :member
    belongs_to :match
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/leader_boards_controller.rb
class LeaderBoardsController < ApplicationController

  def index
  	members_ids = Member.joins(:participants).group('members.id').having("count(participants.id)>=1")
  	@members = Member.where(id: members_ids).includes(:participants).order("participants.score desc").limit(10)
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[ show edit update destroy ]

  # GET /matches or /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1 or /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
    2.times do
      participant = @match.participants.build
    end
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches or /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to match_url(@match), notice: "Match was successfully created." }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to match_url(@match), notice: "Match was successfully updated." }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url, notice: "Match was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.require(:match).permit(:title, :details, :start_date, :end_date, participants_attributes: [:member_id, :score])
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
    matches = @member.participants.pluck(:match_id).uniq
    @win = 0; @los = 0
    Match.where(id: matches).each do |match|
      match.participants.order('score DESC').first.member_id == @member.id ? @win +=1 : @los +=1
    end
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to member_url(@member), notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to member_url(@member), notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :phone_number, :email_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScrabbleClubSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu">
      <li class="menu-text">Scrabble club</li>
      <li>
        <a href="/leader_boards">Leader Board</a>
      </li>
      <li>
        <a href="/members">Member</a>
      </li>
      <li><a href="/matches">Match</a></li>
    </ul>
  </div>
</div>
    <%= yield %>
  </body>
</html>

app/views/leader_boards/index.html.erb

<!-- container-->
<div class="container">
  <h1 class="my-4 text-center text-lg-left">LeaderBoard</h1>
  <table>
  <thead>
    <tr>
      <th>Member</th>
      <th>No of Game</th>
      <th>Aaverage Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @members.each do |member| %>
     <tr>
      <td><%= member.first_name %></td>
      <td><%= member.participants.count %></td>
      <td><%= (member.participants.pluck(:score).sum / member.participants.pluck(:score).count).round%></td>
    </tr>
  <%end%>
  </tbody>
</table>

app/views/matches/_form.html.erb
<%= form_with(model: match, local: true) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <%= form.fields_for :participants do |builder, index| %>
    <br><p>
      <strong>Member <%=index%> <%=index%></strong>
    </p>

    <%= render 'members/member_form', :f => builder %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Matches</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Details</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.title %></td>
        <td><%= match.details %></td>
        <td><%= match.start_date %></td>
        <td><%= match.end_date %></td>
        <td><%= link_to 'Show', match %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
        <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @match.title %>
</p>

<p>
  <strong>Details:</strong>
  <%= @match.details %>
</p>

<p>
  <strong>Participants details:</strong>
</p>

<p>
  <strong>Player 1:</strong>
</p> 
<p>
  <strong>Name :</strong>
  <%= @match.participants.first.member.first_name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @match.participants.first.score %>
</p>

<p>
  <strong>Player 2:</strong>
</p> 
<p>
  <strong>Name :</strong>
  <%= @match.participants.second.member.first_name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @match.participants.second.score %>
</p>

<p>
  <strong>Winer details:</strong>
</p>

<p>
  <strong><%=@match.participants.first.score > @match.participants.second.score ? @match.participants.first.member.first_name : @match.participants.second.member.first_name%> Won the match by <%=@match.participants.first.score > @match.participants.second.score ? @match.participants.first.score : @match.participants.second.score%></strong>
</p> 





<p>
  <strong>Start date:</strong>
  <%= @match.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @match.end_date %>
</p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :email_id %>
    <%= form.text_field :email_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/_member_form.html.erb
 
<div class="field">
<%= f.label "member" %>
<%= f.collection_select(:member_id, Member.all, :id, :first_name, { :prompt => 'Select member'}, { class: 'form-control' }) %>
</div>

<div class="field">
  <%= f.label "member score" %>
  <%= f.number_field :score %>
</div>



app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone number</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.first_name %></td>
        <td><%= member.last_name %></td>
        <td><%= member.phone_number %></td>
        <td><%= member.email_id %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @member.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @member.last_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @member.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email_id %>
</p>
<p>
  <strong>Game details</strong>
</p>

<p>
  <strong>Number of wins: <%=@win%></strong>
</p>

<p>
  <strong>Number of losses: <%=@los%> </strong>
</p>

<p>
  <strong>Average score: <%=@member&.participants.pluck(:score).sum / @member&.participants.pluck(:score).count  if @member&.participants.count > 0 %></strong>
</p>

<p>
  <strong>Highest score: <%=@member&.participants.order('score DESC')&.first&.score || 0%></strong>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>